name:                circular
version:             0.1.0
github:              "dschrempf/circular"
license:             BSD3
author:              "Dominik Schrempf"
maintainer:          "dominik.schrempf@gmail.com"
copyright:           "Dominik Schrempf (2020)"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Circular fixed-sized mutable vectors
category:            Math, Data Structures
description:         Please see the README on GitHub at <https://github.com/dschrempf/circular#readme>

dependencies:
- base >= 4.7 && < 5
- vector

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  circular-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - circular
    - hspec
    - hspec-discover
    - QuickCheck
    - quickcheck-instances
